### PR TITLE
Fix embassy hangs

### LINKED ISSUE #71: Embassy driver for CH32X035 is broken

### PR DESCRIPTION
**Pull request by andelf**
Needs more investigation.

At least x035 works now.

Fix #71

### CODE REVIEW

**Review by mwanner — COMMENTED** [review]
@andelf I can confirm this fixes the blinky examples that use embassy. At least for three devices I tested successfully: ch32v302, ch32x035, and ch32l103.

However, I think this means the entire comment above the function is wrong and needs to be corrected.

I added debug outputs in the two relevant init routines and tried all four variants for configuring `WFITOWFE` and `SEVONPEND`. And embassy based blinking only ever worked with both enabled (following from a ch32l103, but other chips showed same results):

```
no good, no LED blinking:

2024-11-30 23:27:01.044: post qingke_setup_interrupts state: (00000000)
2024-11-30 23:27:01.050: after ch32-hal embassy init:        (00000010)

2024-11-30 23:27:39.990: post qingke_setup_interrupts state: (00000000)
2024-11-30 23:27:39.996: after ch32-hal embassy init:        (00000000)

2024-11-30 23:28:04.196: post qingke_setup_interrupts state: (00000008)
2024-11-30 23:28:04.202: after ch32-hal embassy init:        (00000008)

All good on ch32l103, LED blinking:

2024-11-30 23:28:19.617: post qingke_setup_interrupts state: (00000008)
2024-11-30 23:28:19.623: after ch32-hal embassy init:        (00000018)
```

**Comment by mwanner** [comment]
> ch32v203 is also working.

Sorry, typo in my comment above: I meant to write v203, there is no v302 (AFAIK anyway).

**Comment by Dummyc0m** [comment]
FWIW https://github.com/embassy-rs/embassy/commit/9e6e09a8d747ec90aae215df8471dfe349993487

**Comment by andelf** [comment]
I plan to merge this after addressing the comment fixes. This update will resolve issues with the blinky example and other lower-speed peripherals. And it does not block the spin-executor. @Dummyc0m

**Pull request merged**
