### PR TITLE
feat(otgfs): Implement OTG_FS USB Driver

### PR DESCRIPTION
**Pull request by Codetector1374**
The primary purpose of this change is to introduce an initial
implementation of the USB OTG FS device driver. Although this should
also applie to other SKUs that have the USB FS (without OTG) but those
are currently untested due to the lack of said hardware for testing.

In the process of implementing support for USB, we noticed that the WFI
instruction in the Qingke IP has significant flaws causing the USB
peripheral unable to access memory correctly while the CPU is under WFI.
The exact reason behind this is unclear, but a workaround has been put
inplace by using a new executor we added to embassy named `arch-spin`
which avoids the use of WFI instruction altogether.

Also there were several updates to the peripheral access crate (PAC) to
ensure the USB driver code is as readable as possible. The update may
have not been applied to all device families, especially those using
USB_FS instead of having the full OTG peripheral.

The code has been tested on CH32V307 and CH32V305 with the following
applications:
- USB DFU: mostly to exercise usb control transfer
- USB HID: mostly to exercise usb interrupt transfer

We also provided a simple USB DFU example in the `examples/ch32v307`
directory for those who want to just quickly verify any functionalities.

### CODE REVIEW

**Comment by Codetector1374** [comment]
Ideally this should address some of the concern in #40 as this will now provide a USB_FS example in `examples/ch32v307/usbfs_dfu.rs`

**Comment by Codetector1374** [comment]
Looks like there is a few things failing because some metapac updates aren't done correctly yet. Let me address those soon and get this in a clean state.

**Comment by Codetector1374** [comment]
Test should pass once https://github.com/ch32-rs/ch32-data/pull/9 is merged and I will update the dependency commit hash.

**Comment by Codetector1374** [comment]
Cool now everything should be fixed :) perfect

**Review by andelf — APPROVED** [review]
Excellent work on implementing the USB driver. Let's ship this!

**Pull request merged**
