### PR TITLE
feat: Initial port of HAL from ch32x035 to ch32V307

### PR DESCRIPTION
**Pull request by Marcuss2**
Some changes:

- Another ADC added, rewrote it as a macro
- USBPD removed, so far exclusive to the ch32x series
- USART4 removed, as the CH32V307 does not have it (UART4-8 are asynchronous only) (but the CH32V20x_D6 variation has), UART will have to be added later
- USB stuff appears to be different, so removed it, more investigation will be needed
- Default clock set to 96 MHz, this should provide a good tradeoff between speed and peripheral compatibility
- Changed interrupt initialization
- USART is messy, someone at WCH thought it would be a good idea to divide routing to two separate registers
- Did some dirty pointer casts to ensure register blocks only have one type. Preferably this should be unified into one structure or trait where applicable.
- Fixed timestamp overflow panic in time_driver_systick.rs on line 159

### CODE REVIEW

**Comment by Marcuss2** [comment]
What is left/what I noticed:
-  Second remap of UART2 does not seem to work, could be my board not working or cold solder joint.
-  I haven't tested SPI or UART, I could test the SPI using a Raspberry Pi Pico, but I have no reliable way to generating ADC.

**Comment by Marcuss2** [comment]
Somewhat tested the ADC, it seems that there was a bug preventing it from starting, you have to actually write a single bit to ADON to start it. Fixed it.

**Comment by Marcuss2** [comment]
Tested the SPI and added a simple example for it. I think that is enough for now.

**Comment by andelf** [comment]
This is a lot of work. Well done!

I will take the time to review this.

**Review by andelf — APPROVED** [review]
Let's merge this and start the whole template from this.

**Pull request merged**
